"""AI-callable, non-executing action interface for PC CleanGuard PR10."""

from .actions import (
    ACTION_NAMES,
    SkillActionRequest,
    SkillActionResponse,
    build_cleanup_plan,
    explain_report,
    invoke_skill_action,
    recommend_external_tools,
    quarantine_file_action,
    list_quarantine_items_action,
    restore_quarantine_item_action,
    match_reputation,
    build_pup_insight,
    inspect_pup_risk,
    build_pup_review_pack,
    build_behavior_indicators,
    validate_cn_evidence_pack,
    scan_from_json,
    write_audit,
    write_report,
)
from .cleanup_plan import (
    CleanupPlan,
    CleanupPlanStep,
    READ_ONLY_EXECUTION_LEVEL,
    build_cleanup_plan_from_report,
)

__all__ = [
    "ACTION_NAMES",
    "CleanupPlan",
    "CleanupPlanStep",
    "READ_ONLY_EXECUTION_LEVEL",
    "SkillActionRequest",
    "SkillActionResponse",
    "build_cleanup_plan",
    "build_cleanup_plan_from_report",
    "explain_report",
    "invoke_skill_action",
    "recommend_external_tools",
    "quarantine_file_action",
    "list_quarantine_items_action",
    "restore_quarantine_item_action",
    "match_reputation",
    "build_pup_insight",
    "inspect_pup_risk",
    "build_pup_review_pack",
    "build_behavior_indicators",
    "validate_cn_evidence_pack",
    "scan_from_json",
    "write_audit",
    "write_report",
]
